In [5]:
import math

class Particle:
    """
    這是一個物理質點類別 (Class)
    它像是一個藍圖，定義了所有質點應該有的屬性與行為
    """
    
    def __init__(self, name, mass, velocity):
        """
        初始化方法：當 Instance 被建立時，會自動執行
        self: 代表「這個實體」自己
        """
        self.name = name          # 屬性：名稱
        self.mass = mass          # 屬性：質量 (kg)
        self.velocity = velocity  # 屬性：速度 (m/s)

    def get_kinetic_energy(self):
        """
        這是一個方法 (Method)：計算動能
        公式： Ek = 0.5 * m * v^2
        """
        # 透過 self 存取該實體的屬性
        kinetic_energy = 0.5 * self.mass * (self.velocity ** 2)
        return kinetic_energy

    def describe(self):
        """描述目前質點的狀態"""
        print(f"質點名稱: {self.name}")
        print(f"質量: {self.mass} kg, 目前速度: {self.velocity} m/s")
        print(f"當前動能: {self.get_kinetic_energy()} 焦耳")

# --- 以下是實際應用 (Instance 的建立與操作) ---

# 1. 建立第一個實體 (Instance)
p1 = Particle("質點A", mass=2.0, velocity=10.0)

# 2. 建立第二個實體 (Instance)
p2 = Particle("質點B", mass=5.0, velocity=3.0)

# 3. 呼叫方法與存取屬性
print("--- 執行 p1 的描述 ---")
p1.describe()

print("\n--- 執行 p2 的描述 ---")
p2.describe()


--- 執行 p1 的描述 ---
質點名稱: 質點A
質量: 2.0 kg, 目前速度: 10.0 m/s
當前動能: 100.0 焦耳

--- 執行 p2 的描述 ---
質點名稱: 質點B
質量: 5.0 kg, 目前速度: 3.0 m/s
當前動能: 22.5 焦耳


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print(arr1 * arr2) # 逐元素相乘
# *、/、//、%、** 這些都是逐項元素計算
a1 = np.array([[1],[2],[3]])
a2 = np.array([[1,2,3]])
print(a1@a2) # [[]]才能表示二維，才能做矩陣標準乘法計算

a3 = np.array([1,2,3]) # 這會被當成一維陣列






[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
